// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSHDTZ9DTys18l4c5SAznF5OznRnOP3Ww',
    appId: '1:90025066640:web:1c61e3be7b6e327461d815',
    messagingSenderId: '90025066640',
    projectId: 'lockapplication-d4243',
    authDomain: 'lockapplication-d4243.firebaseapp.com',
    storageBucket: 'lockapplication-d4243.firebasestorage.app',
    measurementId: 'G-6WP8P7QLS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZdnGe1yhtGIKA0Ld-PzN55aZpS-mObpc',
    appId: '1:90025066640:android:b498c2c335953fb761d815',
    messagingSenderId: '90025066640',
    projectId: 'lockapplication-d4243',
    storageBucket: 'lockapplication-d4243.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVhxsoyopEb6Yo26AAferAN1kJTFEj1f0',
    appId: '1:90025066640:ios:d7de69206a740eff61d815',
    messagingSenderId: '90025066640',
    projectId: 'lockapplication-d4243',
    storageBucket: 'lockapplication-d4243.firebasestorage.app',
    iosBundleId: 'com.example.lockApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVhxsoyopEb6Yo26AAferAN1kJTFEj1f0',
    appId: '1:90025066640:ios:d7de69206a740eff61d815',
    messagingSenderId: '90025066640',
    projectId: 'lockapplication-d4243',
    storageBucket: 'lockapplication-d4243.firebasestorage.app',
    iosBundleId: 'com.example.lockApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSHDTZ9DTys18l4c5SAznF5OznRnOP3Ww',
    appId: '1:90025066640:web:328c0ceb833e332d61d815',
    messagingSenderId: '90025066640',
    projectId: 'lockapplication-d4243',
    authDomain: 'lockapplication-d4243.firebaseapp.com',
    storageBucket: 'lockapplication-d4243.firebasestorage.app',
    measurementId: 'G-7J0NZH3RHJ',
  );
}
